package com.example.headerdecoration

object ContactsStore {
    fun getContacts(): MutableList<SimpleItem> {
        return mutableListOf(
            SimpleItem(
                0,
                "Alberto"
            ),
            SimpleItem(
                0,
                "Aldo"
            ),
            SimpleItem(
                0,
                "Alessandro"
            ),
            SimpleItem(
                0,
                "Alice"
            ),
            SimpleItem(
                0,
                "Carlo"
            ),
            SimpleItem(
                0,
                "Carmela"
            ),
            SimpleItem(
                0,
                "Carmine"
            ),
            SimpleItem(
                0,
                "Daniela"
            ),
            SimpleItem(
                0,
                "Daniele"
            ),
            SimpleItem(
                0,
                "Dario"
            ),
            SimpleItem(
                0,
                "Davide"
            ),
            SimpleItem(
                0,
                "Fausto"
            ),
            SimpleItem(
                0,
                "Federica"
            ),
            SimpleItem(
                0,
                "Francesco"
            ),
            SimpleItem(
                0,
                "Fulvio"
            ),
            SimpleItem(
                0,
                "Giacomo"
            ),
            SimpleItem(
                0,
                "Giovanni"
            ),
            SimpleItem(
                0,
                "Ilaria"
            ),
            SimpleItem(
                0,
                "Innocenzo"
            ),
            SimpleItem(
                0,
                "Irene"
            ),
            SimpleItem(
                0,
                "Lidia"
            )
        )
    }
}